#! /bin/sh

nitrogen --restore &
compton --config ~/.config/i3/compton.conf &
bash /home/v16/.config/polybar/init.sh &


sxhkd &

bspc monitor DP-1 -d I II III IV V
bspc monitor DP-2 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Google-chrome" desktop=^6
bspc rule -a "Firefox" desktop=^6
bspc rule -a "Code" desktop=^1
bspc rule -a "Telegram" desktop=^3
bspc rule -a "discord" desktop=^3
bspc rule -a "Spotify" desktop=^7
